# Generated by Django 4.0.5 on 2022-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floraduoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='imagen',
            field=models.ImageField(null=True, upload_to='floras'),
        ),
    ]
